# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dvt.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="dvt.proto",
    package="ClxDVT",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\tdvt.proto\x12\x06\x43lxDVT"\x19\n\x06\x43mdMsg\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t"\x12\n\x10\x43lingResetParams"\x93\x01\n\x0bResultValue\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.ClxDVT.ProcessResultStatus\x12%\n\x04type\x18\x02 \x01(\x0e\x32\x17.ClxDVT.ResultValueType\x12\x0f\n\x07isValid\x18\x03 \x01(\x08\x12\x0e\n\x06output\x18\x04 \x01(\t\x12\x0f\n\x07ret_int\x18\x05 \x01(\x05*w\n\x0fResultValueType\x12\x16\n\x12RET_VLAUE_TYPE_INT\x10\x00\x12\x17\n\x13RET_VLAUE_TYPE_UINT\x10\x01\x12\x18\n\x14RET_VLAUE_TYPE_FLOAT\x10\x02\x12\x19\n\x15RET_VLAUE_TYPE_STRING\x10\x03*W\n\x13ProcessResultStatus\x12\x13\n\x0fPROCESS_SUCCESS\x10\x00\x12\x13\n\x0fPROCESS_FAILURE\x10\x01\x12\x16\n\x12PROCESS_MORE_INPUT\x10\x02\x32\xae\x01\n\x03\x44VT\x12\x30\n\x07process\x12\x0e.ClxDVT.CmdMsg\x1a\x13.ClxDVT.ResultValue"\x00\x12\x35\n\x0c\x61pply_config\x12\x0e.ClxDVT.CmdMsg\x1a\x13.ClxDVT.ResultValue"\x00\x12>\n\x0b\x63ling_reset\x12\x18.ClxDVT.ClingResetParams\x1a\x13.ClxDVT.ResultValue"\x00\x62\x06proto3',
)

_RESULTVALUETYPE = _descriptor.EnumDescriptor(
    name="ResultValueType",
    full_name="ClxDVT.ResultValueType",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="RET_VLAUE_TYPE_INT",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="RET_VLAUE_TYPE_UINT",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="RET_VLAUE_TYPE_FLOAT",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="RET_VLAUE_TYPE_STRING",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=218,
    serialized_end=337,
)
_sym_db.RegisterEnumDescriptor(_RESULTVALUETYPE)

ResultValueType = enum_type_wrapper.EnumTypeWrapper(_RESULTVALUETYPE)
_PROCESSRESULTSTATUS = _descriptor.EnumDescriptor(
    name="ProcessResultStatus",
    full_name="ClxDVT.ProcessResultStatus",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="PROCESS_SUCCESS",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="PROCESS_FAILURE",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="PROCESS_MORE_INPUT",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=339,
    serialized_end=426,
)
_sym_db.RegisterEnumDescriptor(_PROCESSRESULTSTATUS)

ProcessResultStatus = enum_type_wrapper.EnumTypeWrapper(_PROCESSRESULTSTATUS)
RET_VLAUE_TYPE_INT = 0
RET_VLAUE_TYPE_UINT = 1
RET_VLAUE_TYPE_FLOAT = 2
RET_VLAUE_TYPE_STRING = 3
PROCESS_SUCCESS = 0
PROCESS_FAILURE = 1
PROCESS_MORE_INPUT = 2


_CMDMSG = _descriptor.Descriptor(
    name="CmdMsg",
    full_name="ClxDVT.CmdMsg",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="command",
            full_name="ClxDVT.CmdMsg.command",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=21,
    serialized_end=46,
)


_CLINGRESETPARAMS = _descriptor.Descriptor(
    name="ClingResetParams",
    full_name="ClxDVT.ClingResetParams",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=48,
    serialized_end=66,
)


_RESULTVALUE = _descriptor.Descriptor(
    name="ResultValue",
    full_name="ClxDVT.ResultValue",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="status",
            full_name="ClxDVT.ResultValue.status",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="type",
            full_name="ClxDVT.ResultValue.type",
            index=1,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="isValid",
            full_name="ClxDVT.ResultValue.isValid",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="output",
            full_name="ClxDVT.ResultValue.output",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="ret_int",
            full_name="ClxDVT.ResultValue.ret_int",
            index=4,
            number=5,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=69,
    serialized_end=216,
)

_RESULTVALUE.fields_by_name["status"].enum_type = _PROCESSRESULTSTATUS
_RESULTVALUE.fields_by_name["type"].enum_type = _RESULTVALUETYPE
DESCRIPTOR.message_types_by_name["CmdMsg"] = _CMDMSG
DESCRIPTOR.message_types_by_name["ClingResetParams"] = _CLINGRESETPARAMS
DESCRIPTOR.message_types_by_name["ResultValue"] = _RESULTVALUE
DESCRIPTOR.enum_types_by_name["ResultValueType"] = _RESULTVALUETYPE
DESCRIPTOR.enum_types_by_name["ProcessResultStatus"] = _PROCESSRESULTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmdMsg = _reflection.GeneratedProtocolMessageType(
    "CmdMsg",
    (_message.Message,),
    {
        "DESCRIPTOR": _CMDMSG,
        "__module__": "dvt_pb2"
        # @@protoc_insertion_point(class_scope:ClxDVT.CmdMsg)
    },
)
_sym_db.RegisterMessage(CmdMsg)

ClingResetParams = _reflection.GeneratedProtocolMessageType(
    "ClingResetParams",
    (_message.Message,),
    {
        "DESCRIPTOR": _CLINGRESETPARAMS,
        "__module__": "dvt_pb2"
        # @@protoc_insertion_point(class_scope:ClxDVT.ClingResetParams)
    },
)
_sym_db.RegisterMessage(ClingResetParams)

ResultValue = _reflection.GeneratedProtocolMessageType(
    "ResultValue",
    (_message.Message,),
    {
        "DESCRIPTOR": _RESULTVALUE,
        "__module__": "dvt_pb2"
        # @@protoc_insertion_point(class_scope:ClxDVT.ResultValue)
    },
)
_sym_db.RegisterMessage(ResultValue)


_DVT = _descriptor.ServiceDescriptor(
    name="DVT",
    full_name="ClxDVT.DVT",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=429,
    serialized_end=603,
    methods=[
        _descriptor.MethodDescriptor(
            name="process",
            full_name="ClxDVT.DVT.process",
            index=0,
            containing_service=None,
            input_type=_CMDMSG,
            output_type=_RESULTVALUE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="apply_config",
            full_name="ClxDVT.DVT.apply_config",
            index=1,
            containing_service=None,
            input_type=_CMDMSG,
            output_type=_RESULTVALUE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="cling_reset",
            full_name="ClxDVT.DVT.cling_reset",
            index=2,
            containing_service=None,
            input_type=_CLINGRESETPARAMS,
            output_type=_RESULTVALUE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_DVT)

DESCRIPTOR.services_by_name["DVT"] = _DVT

# @@protoc_insertion_point(module_scope)
