default_stages: [commit]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: flake8
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-json
  - id: check-yaml
  - id: debug-statements
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  - id: check-case-conflict

- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports

